version: 0.0
os: linux
files:
  - source: /  # Path to your source code
    destination: /var/www/html  # Destination directory on EC2 instance

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

