version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "nodejs-app"          # Your ECR repo name
    CONTAINER_NAME: "nodejs-container"     # ECS container name in task definition

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      echo Installing Node.js dependencies...
      npm install

  pre_build:
    commands:
      echo Logging in to Amazon ECR...
      aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      echo Building the Docker image...
      docker build -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_URI/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      echo Pushing Docker image to ECR...
      docker push $ECR_URI/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      echo Writing imagedefinitions.json for ECS deployment...
      printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$ECR_URI/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION" > imagedefinitions.json
      echo Build completed on `date`

artifacts:
  files:
    - imagedefinitions.json

